/* @flow */

export const ACTION = {
  FETCH_SHIFTS_LOADING: 'FETCH_SHIFTS_LOADING',
  FETCH_SHIFTS_SUCCESS: 'FETCH_SHIFTS_SUCCESS',
  FETCH_SHIFTS_FAIL: 'FETCH_SHIFTS_FAIL',

  FETCH_EMPLOYEES_LOADING: 'FETCH_EMPLOYEES_LOADING',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
  FETCH_EMPLOYEES_FAIL: 'FETCH_EMPLOYEES_FAIL',
};