// @flow

export const ACTION = {
  FETCH_SHIFTS_REQUESTED: 'FETCH_SHIFTS_REQUESTED',
  FETCH_SHIFTS_LOADING: 'FETCH_SHIFTS_LOADING',
  FETCH_SHIFTS_SUCCESS: 'FETCH_SHIFTS_SUCCESS',
  FETCH_SHIFTS_FAIL: 'FETCH_SHIFTS_FAIL',
};